### ISSUE TITLE
🛑 SV3 is down

### ISSUE THREAD

**Issue by site-kanshi** [yamagami2211/site-kanshi#4]
In [`63b88a3`](https://github.com/yamagami2211/site-kanshi/commit/63b88a35242e8ff12b9a634c413bd56640f68b5e
), SV3 (http://sv03-vps.yama2211.jp) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by yamagami2211** [comment]
Mysqlのアップデート作業のため、数分間停止していました。作業は完了しています。
