### ISSUE TITLE
🛑 SV1 is down

### ISSUE THREAD

**Issue by site-kanshi** [yamagami2211/site-kanshi#5]
In [`fae56a5`](https://github.com/yamagami2211/site-kanshi/commit/fae56a58b28df7205e18779a3b061f5566326106
), SV1 (http://sv01-vps.yama2211.jp) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by yamagami2211** [comment]
phpMyAdminのアップデートのため一時的に停止していました。
現在も作業中のため、何度か停止->起動を繰り返す可能性があります。
